// Comprehensive list of Lebanese cities, towns and villages used as the
// canonical "location" set across BEITAK.
export const LEBANESE_LOCATIONS = [
  // Major cities
  "Beirut",
  "Tripoli",
  "Sidon (Saida)",
  "Tyre (Sour)",
  "Baalbek",
  "Zahle",
  "Jounieh",
  "Byblos (Jbeil)",
  "Aley",
  "Broummana",
  "Faraya",
  "Bcharre",
  "Ehden",
  "Zgharta",
  "Deir el Qamar",
  // Mountain & coastal towns
  "Batroun",
  "Amioun",
  "Anjar",
  "Beit Mery",
  "Beiteddine",
  "Bkerke",
  "Chouf",
  "Chtoura",
  "Hasbaya",
  "Hermel",
  "Jezzine",
  "Kfardebian",
  "Kfarhouna",
  "Kfarhata",
  "Marjayoun",
  "Mzaar",
  "Nabatieh",
  "Rachaya",
  "Tannourine",
  "Hammana",
  "Bikfaya",
  "Dhour Choueir",
  "Sawfar",
  "Falougha",
  "Bhamdoun",
  "Ainab",
  "Aitaroun",
  "Akkar",
  "Halba",
  "Kobayat",
  "Andket",
  "Aabey",
  "Aitanit",
  "Baakleen",
  "Barouk",
  "Maaser el Chouf",
  "Niha",
  "Mtein",
  "Qartaba",
  "Lehfed",
  "Qornet el Hamra",
  "Beit Chabab",
  "Bsharri",
  "Hasroun",
  "Hadath el Jebbeh",
  "Kfardlakos",
  "Tourza",
  "Bane",
  "Kousba",
  "Bteghrine",
  "Kornet Chehwan",
  "Rabieh",
  "Antelias",
  "Dbayeh",
  "Zalka",
  "Jal el Dib",
  "Hazmieh",
  "Baabda",
  "Khaldeh",
  "Damour",
  "Naameh",
  "Ghazir",
  "Tabarja",
  "Zouk Mosbeh",
  "Adma",
  "Halat",
  "Amchit",
  "Chekka",
  "Enfeh",
  "Kfarabida",
  "Ghazieh",
  "Sarafand",
  "Qana",
  "Bint Jbeil",
  "Tibnine",
  "Naqoura",
  "Rmeich",
  "Aitanit",
  "Chebaa",
  "Kfar Kila",
  "Khiam",
  "Barja",
  "Choueifat",
  "Souk el Gharb",
  "Mansourieh",
  "Beit Chaar",
  "Roumieh",
  "Dhour Chweir",
  "Mayrouba",
  "Aaqoura",
  "Laklouk",
  "Cedars",
] as const;

export type LebaneseLocation = (typeof LEBANESE_LOCATIONS)[number];

export const POPULAR_DESTINATIONS: { name: string; description: string }[] = [
  { name: "Beirut", description: "The capital, alive day and night" },
  { name: "Byblos (Jbeil)", description: "7,000 years of history by the sea" },
  { name: "Baalbek", description: "Roman ruins in the Bekaa Valley" },
  { name: "Faraya", description: "Snow & ski escapes" },
  { name: "Bcharre", description: "Cedars and Gibran's village" },
  { name: "Tyre (Sour)", description: "Phoenician coast & beaches" },
  { name: "Jounieh", description: "Mediterranean bay & nightlife" },
  { name: "Deir el Qamar", description: "Stone-built mountain heritage" },
];
